api_keys:
  dialogflow: ""
  luis: ""
  qna_maker: ""

databases:
  main:
    host: "localhost"
    port: 5432
    name: "assistant_db"

speech:
  google:
    credentials: ${GOOGLE_CREDENTIALS}

search:
  engines:
    default: "google"  # Motor por defecto
    current: "google"  # Motor actualmente seleccionado
    proxy: ""         # Proxy opcional para las búsquedas
    google:
      base_url: "https://www.google.com/search"
      params:
        hl: "es"      # Idioma
        lr: "lang_es" # Resultados en español
        safe: "off"   # Filtro de SafeSearch
      selectors:
        result: "div.g"
        title: "h3"
        link: "a"
        snippet: "div.VwiC3b"
    bing:
      base_url: "https://www.bing.com/search"
      selectors:
        result: "li.b_algo"
        title: "h2"
        link: "a"
        snippet: "div.b_caption"
    duckduckgo:
      base_url: "https://html.duckduckgo.com/html"
      selectors:
        result: ".result"
        title: ".result__title"
        link: ".result__url"
        snippet: ".result__snippet"

  user_agents:
    default: "chrome"  # Agente por defecto
    current: "chrome"  # Agente actualmente seleccionado
    rotate: true       # Rotar automáticamente
    interval: 10       # Cambiar cada N búsquedas
    agents:
      chrome:
        - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      firefox:
        - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
        - "Mozilla/5.0 (X11; Linux i686; rv:121.0) Gecko/20100101 Firefox/121.0"
      edge:
        - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
      mobile:
        - "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1"
        - "Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.210 Mobile Safari/537.36"
        
  headers:
    accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    accept_language: "es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3"
    accept_encoding: "gzip, deflate, br"
    connection: "keep-alive"
    dnt: "1"

cache:
  base_dir: "data/cache"
  max_age_days: 7
  dirs:
    - documents
    - images
    - audio
    - video
    - search
  clean_interval: 86400  # 24 horas en segundos
